spring.datasource.url= jdbc:postgresql://localhost:5432/TelegramBot
spring.datasource.username= student
spring.datasource.password= chocolatefrog
telegram.bot.token= 8526493486:AAHLGRvVIVgOVdZEyn6a0bsLpQWeootzZsY
spring.jpa.hibernate.ddl-auto= validate
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml